spring:
  application:
    name: BrainWorksExams
  datasource:
    url: jdbc:mysql://localhost:3306/exams?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: embedded
  profiles:
    active:
    - ${active_profile:qa}
server:
  port: 8080
  servlet:
    context-path: /exam-api/

jwt:
  secret : ThisIsSomeComplexKey

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka

logging:
  level:
    '[com.brainworksexams]': DEBUG
    '[org.springframework.web]': INFO
    '[org.hibernate.type.descriptor.sql]': INFO
    '[org.springframework.security]': INFO
    
springdoc:
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: true
